# Task 3

name: JSG5 - multiple jobs + secret

# Controls when the workflow will run
on:
  # Triggers the workflow if a comment is created
  discussion_comment:
      types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Greeting1: Well, hello
  Greeting2: Good bye
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  greeting_one:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository code # Best practice: always checkout first
      uses: actions/checkout@v4      # This step checks out the code.
  
    - name: Say hello no 1
      run: echo $Greeting1
  
  greeting_two:
    runs-on: ubuntu-latest
    needs: greeting_one
    steps:
      - name: Checkout repository code # Best practice: always checkout first
        uses: actions/checkout@v4      # This step checks out the code.
      - name: Hello no 2 with secret
        run: echo {{ $env.Greeting2 }} and ${{ secrets.DAY1_EXERCSISE_SECRET }}
